name: Deploy Eleventy to GitHub Pages

on:
  push:
    branches:
      - Narmeenk  # Replace with your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x  # Flexible version for Node.js 20

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Build the site using Eleventy
    - name: Build site
      run: npm build  # Direct Eleventy build command

    # Step 5: Deploy the _site folder to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _site  # This is the build folder
